type HtmlOptions = { readonly nonce: string; readonly serverName: string; readonly readOnly?: boolean };
type MarkupOptions = { readonly serverName: string; readonly readOnly: boolean; readonly initialSql: string };
type ScriptOptions = { readonly nonce: string };

const INITIAL_ROW_LIMIT = 200;
const MAX_RENDER_ROWS = 10_000;
const DEFAULT_INITIAL_SQL = 'SELECT * FROM information_schema.tables LIMIT 10;';

export function buildQueryWorkbenchHtml(options: HtmlOptions): string {
    return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${options.nonce}';">
<title>SQL Workbench</title><style>
${buildWorkbenchStyles()}
</style></head><body>${buildWorkbenchMarkup({ serverName: options.serverName, readOnly: options.readOnly === true, initialSql: DEFAULT_INITIAL_SQL })}${buildWorkbenchScript({ nonce: options.nonce })}</body></html>`;
}

export function buildWorkbenchStyles(): string {
    return `*{box-sizing:border-box}html,body{height:100%;margin:0}body{font:13px var(--vscode-font-family);color:var(--vscode-foreground);background:var(--vscode-sideBar-background);overflow:hidden}
button,select{font:inherit;color:var(--vscode-button-foreground);background:var(--vscode-button-background);border:1px solid transparent;border-radius:2px;padding:5px 10px;transition:background-color 120ms ease,border-color 120ms ease}button:hover{background:var(--vscode-button-hoverBackground)}button:focus-visible,select:focus-visible,input:focus-visible{outline:1px solid var(--vscode-focusBorder);outline-offset:1px}button.secondary{color:var(--vscode-foreground);background:var(--vscode-button-secondaryBackground);border-color:var(--vscode-panel-border)}button:disabled,select:disabled{cursor:not-allowed;opacity:.55;border-color:var(--vscode-panel-border)}
#app{height:100%;padding:12px;display:grid;gap:10px;grid-template-columns:minmax(0,1fr) minmax(260px,29vw);grid-template-rows:auto minmax(190px,38vh) minmax(0,1fr);background:radial-gradient(circle at 10% 0,var(--vscode-editor-lineHighlightBackground),transparent 36%)}.topbar{grid-column:1/-1;display:flex;flex-wrap:wrap;align-items:center;gap:6px 10px;min-width:0;padding:7px 10px;border:1px solid var(--vscode-panel-border);border-radius:3px;background:var(--vscode-editor-background)}.brand{font-size:12px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--vscode-charts-purple)}.server{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-family:var(--vscode-editor-font-family);color:var(--vscode-foreground)}.connection-context{display:flex;align-items:center;gap:8px;min-width:0}.connection-context::before{content:'';width:8px;height:8px;border-radius:50%;background:var(--vscode-charts-blue)}
.ro-badge{display:inline-block;padding:1px 6px;border:1px solid var(--vscode-charts-blue);border-radius:2px;font-size:9px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--vscode-charts-blue);background:transparent;flex:none}
.editor-pane{position:relative;min-width:0;min-height:0;padding:8px;border:1px solid var(--vscode-panel-border);border-radius:3px;background:var(--vscode-editorGroupHeader-tabsBackground)}.editor-pane::before{content:'SQL editor';position:absolute;z-index:2;inset:13px auto auto 17px;font-size:10px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:var(--vscode-charts-blue)}.editor-shell{position:relative;min-height:0;height:100%;overflow:hidden;border:1px solid var(--vscode-panel-border);border-radius:2px;background:var(--vscode-editor-background)}.editor{display:block;width:100%;height:100%;min-height:160px;margin:0;padding:34px 14px 48px;border:0;white-space:pre-wrap;overflow:auto;font:14px/1.55 var(--vscode-editor-font-family);tab-size:4;resize:none;background:var(--vscode-editor-background);color:var(--vscode-editor-foreground);caret-color:var(--vscode-editorCursor-foreground)}.editor:focus{outline:1px solid var(--vscode-focusBorder);outline-offset:-1px}.editor::selection{background:var(--vscode-editor-selectionBackground)}
.editor-tools{position:absolute;left:0;right:0;bottom:0;display:flex;gap:6px;align-items:center;padding:7px 9px;border-top:1px solid var(--vscode-panel-border);background:var(--vscode-editorGroupHeader-tabsBackground)}.editor-tools #run{border-color:var(--vscode-charts-purple)}.spacer{flex:1}.autocomplete{position:absolute;z-index:8;display:none;max-height:180px;min-width:220px;overflow:auto;border:1px solid var(--vscode-widget-border);border-radius:2px;background:var(--vscode-editorSuggestWidget-background);box-shadow:0 8px 24px var(--vscode-widget-shadow)}.autocomplete button{display:block;width:100%;text-align:left;border-radius:0;color:var(--vscode-editorSuggestWidget-foreground);background:transparent}.autocomplete button.active{background:var(--vscode-editorSuggestWidget-selectedBackground)}
.results-pane{min-width:0;min-height:0;overflow:auto;position:relative;border:1px solid var(--vscode-panel-border);border-radius:3px;background:var(--vscode-editor-background)}.statusbar{position:sticky;top:0;z-index:6;display:flex;flex-wrap:wrap;gap:6px 16px;padding:7px 10px;border-bottom:1px solid var(--vscode-panel-border);background:var(--vscode-editorGroupHeader-tabsBackground);color:var(--vscode-descriptionForeground);font-size:11px;font-variant-numeric:tabular-nums}#cards{padding:10px}.empty{padding:30px;text-align:center;color:var(--vscode-descriptionForeground)}.card{margin-bottom:10px;border:1px solid var(--vscode-panel-border);border-left:2px solid var(--vscode-charts-purple);border-radius:2px;overflow:hidden;background:var(--vscode-editor-background)}.card-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:4px 12px;align-items:center;padding:8px 10px;background:var(--vscode-editor-lineHighlightBackground)}.card-head::before{content:'Statement';grid-column:1;font-size:10px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:var(--vscode-charts-blue)}.sql-label{grid-column:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-family:var(--vscode-editor-font-family);font-weight:600}.meta{grid-column:2;grid-row:1/3;white-space:nowrap;color:var(--vscode-descriptionForeground);font-variant-numeric:tabular-nums}.table-scroll{height:300px;overflow:auto;position:relative}.virtual-pad{position:relative;min-width:max-content}.virtual-table{position:absolute;top:0;left:0;border-collapse:collapse;min-width:100%;table-layout:fixed}th,td{height:30px;padding:5px 9px;border-right:1px solid var(--vscode-panel-border);border-bottom:1px solid var(--vscode-panel-border);max-width:420px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-align:left}th{position:sticky;top:0;z-index:3;background:var(--vscode-editorGroupHeader-tabsBackground)}tr:hover td{background:var(--vscode-list-hoverBackground)}.more{margin:8px}.error{padding:12px;color:var(--vscode-errorForeground);background:var(--vscode-inputValidation-errorBackground)}.explain{padding:8px}.node{padding:5px 8px;border-left:1px solid var(--vscode-tree-indentGuidesStroke);font-family:var(--vscode-editor-font-family)}
.sidebar{grid-column:2;grid-row:2/4;min-height:0;border:1px solid var(--vscode-panel-border);border-radius:3px;background:var(--vscode-editor-background);overflow:auto}.side-head{position:sticky;top:32px;padding:8px 10px;font-size:11px;font-weight:600;letter-spacing:.04em;text-transform:uppercase;background:var(--vscode-sideBarSectionHeader-background);color:var(--vscode-descriptionForeground)}.history-item{display:block;width:100%;padding:9px 10px;text-align:left;color:var(--vscode-sideBar-foreground);background:transparent;border:0;border-radius:0;border-bottom:1px solid var(--vscode-panel-border)}.history-item:hover{background:var(--vscode-list-hoverBackground)}.history-sql{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-family:var(--vscode-editor-font-family)}.history-time{font-size:10px;color:var(--vscode-descriptionForeground);font-variant-numeric:tabular-nums}#detail{padding:12px;white-space:pre-wrap;overflow-wrap:anywhere;font-family:var(--vscode-editor-font-family)}.tabs{position:sticky;top:0;z-index:4;display:flex;border-bottom:1px solid var(--vscode-panel-border);background:var(--vscode-editor-background)}.tabs button{flex:1;border:0;border-radius:0;background:transparent;color:var(--vscode-foreground)}.tabs button.active{box-shadow:inset 0 -2px var(--vscode-charts-purple);color:var(--vscode-foreground)}.hidden{display:none!important}
@media(max-width:760px){body{overflow:auto}#app{height:auto;min-height:100%;grid-template-columns:minmax(0,1fr);grid-template-rows:auto minmax(250px,42vh) minmax(240px,auto) minmax(180px,auto);padding:8px}.topbar{align-items:flex-start;flex-wrap:wrap}.editor-pane{grid-row:2}.results-pane{grid-row:3;overflow:visible}.sidebar{display:block;grid-column:1;grid-row:4;max-height:320px}}
button.open-session{padding:9px 18px;border-color:var(--vscode-charts-purple);color:var(--vscode-button-foreground);background:var(--vscode-button-background);font-weight:600;font-size:13px;border-radius:2px;cursor:pointer;transition:background-color 120ms ease,border-color 120ms ease}button.open-session:hover{background:var(--vscode-button-hoverBackground);border-color:var(--vscode-charts-purple)}button.open-session:focus-visible{outline:1px solid var(--vscode-focusBorder);outline-offset:1px}.empty-tagline{margin:0 0 12px 0;color:var(--vscode-descriptionForeground);font-size:12px;line-height:1.4}.empty-action{padding:30px 24px;text-align:center}.empty-action.hidden{display:none}`;
}

export function buildWorkbenchMarkup(options: MarkupOptions): string {
    const server = options.serverName;
    const initialSql = options.initialSql
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
    // The RO badge is rendered in the connection-context pill next to the
    // server name so the user always sees the active safety posture before
    // hitting Run. The aria-label includes "read-only" for assistive tech.
    const roBadge = options.readOnly
        ? '<span class="ro-badge" title="This server is in read-only mode. Writes are rejected by the server.">RO</span>'
        : '';
    const contextLabel = options.readOnly
        ? `Connected server: ${server} (read-only)`
        : `Connected server: ${server}`;
    return `<div id="app">
<header class="topbar"><span class="brand">Query Studio</span><span class="connection-context" aria-label="${contextLabel}"><span class="server">${server}</span>${roBadge}</span></header>
<section class="editor-pane"><div class="editor-shell"><textarea id="editor" class="editor" spellcheck="false" aria-label="SQL editor">${initialSql}</textarea><div id="autocomplete" class="autocomplete"></div><div class="editor-tools"><button id="run" disabled>Run</button><button id="explain" class="secondary" disabled>Explain</button><select id="export" aria-label="Export results" disabled><option value="">Export…</option><option value="csv">CSV</option><option value="json">JSON</option><option value="md">Markdown</option></select></div></div></section>
<main class="results-pane" aria-live="polite"><div class="statusbar"><span>Server: ${server}${options.readOnly ? ' · RO' : ''}</span><span id="last-time">Time: —</span><span id="last-rows">Rows: —</span></div><div id="cards"><div class="empty empty-action"><p class="empty-tagline">Click to start querying — credentials cached for next time.</p><button id="open-session" class="open-session" type="button">Open Session</button></div></div></main>
<aside class="sidebar"><div class="tabs"><button id="history-tab" class="active">History</button><button id="detail-tab">Cell detail</button></div><section id="history"><div class="side-head">Recent queries</div><div id="history-list"></div><button id="history-more" class="secondary hidden">Load more</button></section><section id="detail-panel" class="hidden"><div class="side-head" id="detail-title">Cell detail</div><div id="detail">Select a result cell.</div></section></aside>
</div>`;
}

/* eslint-disable no-useless-escape */
export function buildWorkbenchScript(options: ScriptOptions): string {
    return `<script nonce="${options.nonce}">
const vscode=acquireVsCodeApi();const editor=document.getElementById('editor');const cards=document.getElementById('cards');const autocomplete=document.getElementById('autocomplete');
const state={results:[],sql:[],selected:0,completions:[],historyOffset:0};
function esc(value){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function prepareRun(){if(!editor.value.trim())return false;state.results=[];state.sql=[];cards.innerHTML='';return true;}
function run(){if(!prepareRun())return;vscode.postMessage({command:'executeQuery',sql:editor.value});}
function runFocused(){if(!prepareRun())return;vscode.postMessage({command:'runFocusedQuery',sql:editor.value,caret:editor.selectionStart});}
function saveSnippet(){const blob=new Blob([editor.value],{type:'text/sql'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='query-'+new Date().toISOString().replace(/[:.]/g,'-')+'.sql';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);}
function valueText(value){if(value===null)return'NULL';if(typeof value==='object')return JSON.stringify(value);return String(value);}
function showCard(message,explain){const data=message.data;state.results[message.statementIndex]=data;state.sql[message.statementIndex]=message.statement||'';const old=document.getElementById('card-'+message.statementIndex);if(old)old.remove();const placeholder=document.getElementById('loading-placeholder');if(placeholder)placeholder.remove();const card=document.createElement('section');card.className='card';card.id='card-'+message.statementIndex;const title='<div class="card-head"><span class="sql-label">'+esc(message.statement||'Statement '+(message.statementIndex+1))+'</span><span class="meta">'+data.rowCount+' rows · '+data.executionTime+' ms</span></div>';card.innerHTML=title;if(data.error){card.innerHTML+='<div class="error">'+esc(data.error)+'</div>';}else if(explain){renderExplain(card,data);}else if(!data.columns.length){card.innerHTML+='<div class="empty">Statement completed successfully.</div>';}else{renderVirtual(card,message.statementIndex,data,Math.min(INITIAL_LIMIT,data.rows.length));}cards.appendChild(card);document.getElementById('last-time').textContent='Time: '+data.executionTime+' ms';document.getElementById('last-rows').textContent='Rows: '+data.rowCount;syncButtons();}
const INITIAL_LIMIT=${INITIAL_ROW_LIMIT},MAX_ROWS=${MAX_RENDER_ROWS},ROW_HEIGHT=30;
function renderVirtual(card,index,data,limit){const wrap=document.createElement('div');wrap.className='table-scroll';const pad=document.createElement('div');pad.className='virtual-pad';wrap.appendChild(pad);card.appendChild(wrap);const shown=Math.min(limit,data.rows.length,MAX_ROWS);pad.style.height=(shown*ROW_HEIGHT+ROW_HEIGHT)+'px';function draw(){const start=Math.max(0,Math.floor(wrap.scrollTop/ROW_HEIGHT)-5);const count=Math.ceil(wrap.clientHeight/ROW_HEIGHT)+10;const end=Math.min(shown,start+count);const table=document.createElement('table');table.className='virtual-table';table.style.top=(start*ROW_HEIGHT)+'px';table.innerHTML='<thead><tr>'+data.columns.map(col=>'<th>'+esc(col)+'</th>').join('')+'</tr></thead><tbody>'+data.rows.slice(start,end).map((row,rowOffset)=>'<tr>'+data.columns.map(col=>'<td data-row="'+(start+rowOffset)+'" data-col="'+esc(col)+'" title="Open cell detail">'+esc(valueText(row[col]))+'</td>').join('')+'</tr>').join('')+'</tbody>';pad.replaceChildren(table);}wrap.addEventListener('scroll',draw);wrap.addEventListener('click',event=>{const cell=event.target.closest('td');if(cell)vscode.postMessage({command:'showCellDetail',statementIndex:index,rowIndex:Number(cell.dataset.row),column:cell.dataset.col});});draw();if(data.rows.length>INITIAL_LIMIT&&limit<=INITIAL_LIMIT){const more=document.createElement('button');more.className='more secondary';more.textContent='Show all ('+Math.min(data.rows.length,MAX_ROWS).toLocaleString()+' rows)';more.onclick=()=>vscode.postMessage({command:'loadMore',statementIndex:index});card.appendChild(more);}}
function renderExplain(card,data){const table=document.createElement('table');table.className='explain-table';table.innerHTML='<thead><tr>'+data.columns.map(col=>'<th>'+esc(col)+'</th>').join('')+'</tr></thead><tbody>'+data.rows.map(row=>'<tr>'+data.columns.map(col=>'<td>'+esc(valueText(row[col]))+'</td>').join('')+'</tr>').join('')+'</tbody>';const note=document.createElement('p');note.className='explain-note';note.textContent='Execution plan rows from MySQL. Server-reported order; no inferred hierarchy.';card.appendChild(table);card.appendChild(note);}
function requestCompletion(){const before=editor.value.slice(0,editor.selectionStart);if(!/\b(?:FROM|JOIN)\s+[\w$-]*$/i.test(before)&&!/\b[\w$-]+\.[\w$-]*$/.test(before)){hideCompletion();return;}const match=/([\w$-]*)$/.exec(before);vscode.postMessage({command:'loadCompletions',sql:before,prefix:match?match[1]:''});}
function showCompletions(items){state.completions=items;state.selected=0;if(!items.length){hideCompletion();return;}autocomplete.style.display='block';autocomplete.style.left=Math.min(editor.clientWidth-240,20+(editor.selectionStart%80)*8)+'px';autocomplete.style.top='42px';renderCompletion();}
function renderCompletion(){autocomplete.innerHTML=state.completions.map((item,index)=>'<button class="'+(index===state.selected?'active':'')+'" data-index="'+index+'">'+esc(item)+'</button>').join('');}
function acceptCompletion(){const item=state.completions[state.selected];if(!item)return;const before=editor.value.slice(0,editor.selectionStart);const match=/[\w$-]*$/.exec(before);const start=match?editor.selectionStart-match[0].length:editor.selectionStart;editor.setRangeText(item,start,editor.selectionStart,'end');hideCompletion();}
function hideCompletion(){autocomplete.style.display='none';state.completions=[];}
function tab(name){const detail=name==='detail';document.getElementById('history').classList.toggle('hidden',detail);document.getElementById('detail-panel').classList.toggle('hidden',!detail);document.getElementById('history-tab').classList.toggle('active',!detail);document.getElementById('detail-tab').classList.toggle('active',detail);}
editor.addEventListener('input',()=>{requestCompletion();syncButtons();});editor.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();runFocused();return;}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();saveSnippet();return;}if(state.completions.length&&['ArrowDown','ArrowUp','Enter','Tab','Escape'].includes(event.key)){event.preventDefault();if(event.key==='ArrowDown')state.selected=(state.selected+1)%state.completions.length;else if(event.key==='ArrowUp')state.selected=(state.selected+state.completions.length-1)%state.completions.length;else if(event.key==='Escape')hideCompletion();else acceptCompletion();renderCompletion();return;}});
autocomplete.addEventListener('mousedown',event=>{const button=event.target.closest('button');if(button){state.selected=Number(button.dataset.index);acceptCompletion();event.preventDefault();}});
document.getElementById('run').addEventListener('click',(event)=>{event.preventDefault();event.stopPropagation();run();});
document.getElementById('explain').addEventListener('click',()=>{if(editor.value.trim())vscode.postMessage({command:'runExplain',sql:editor.value,caret:editor.selectionStart});});
document.getElementById('export').addEventListener('change',event=>{if(event.target.value)vscode.postMessage({command:'export',format:event.target.value});event.target.value='';});
document.getElementById('history-tab').addEventListener('click',()=>tab('history'));
document.getElementById('detail-tab').addEventListener('click',()=>tab('detail'));
document.getElementById('history-more').addEventListener('click',()=>vscode.postMessage({command:'loadHistory',offset:state.historyOffset}));
document.getElementById('open-session').addEventListener('click',()=>vscode.postMessage({command:'openSession'}));
document.addEventListener('keydown',(event)=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();runFocused();}});
window.addEventListener('message',event=>{const message=event.data;switch(message.type){case'loading':cards.innerHTML='<div id="loading-placeholder" class="empty">Executing statements…</div>';break;case'result':break;case'statementResult':showCard(message,false);break;case'explainResult':showCard(message,true);break;case'error':cards.innerHTML='<div class="error">'+esc(message.message)+'</div>';break;case'moreRows':{const data=state.results[message.statementIndex];const card=document.getElementById('card-'+message.statementIndex);if(data&&card){const scroll=card.querySelector('.table-scroll');const more=card.querySelector('.more');if(scroll)scroll.remove();if(more)more.remove();renderVirtual(card,message.statementIndex,{...data,rows:message.rows},message.rows.length);if(message.capped)card.insertAdjacentHTML('beforeend','<div class="error">Display capped at '+MAX_ROWS.toLocaleString()+' rows. Export for the complete result.</div>');}break;}case'cellDetail':document.getElementById('detail-title').textContent=message.column+' · row '+(message.rowIndex+1);document.getElementById('detail').textContent=typeof message.value==='string'?message.value:JSON.stringify(message.value,null,2);tab('detail');break;case'completions':showCompletions(message.items);break;case'history':{const list=document.getElementById('history-list');if(message.offset===0)list.innerHTML='';message.entries.forEach(entry=>{const button=document.createElement('button');button.className='history-item';button.innerHTML='<span class="history-sql">'+esc(entry.sql)+'</span><span class="history-time">'+new Date(entry.executedAt).toLocaleString()+'</span>';button.onclick=()=>{editor.value=entry.sql;editor.focus();syncButtons();};list.appendChild(button);});state.historyOffset=message.offset+message.entries.length;document.getElementById('history-more').classList.toggle('hidden',!message.hasMore);break;}case'setSql':editor.value=message.sql||'';editor.focus();editor.setSelectionRange(editor.value.length,editor.value.length);syncButtons();break;case'sessionState':{const openBtn=document.getElementById('open-session');if(openBtn){openBtn.classList.toggle('hidden',!!message.connected);}break;}}});
function syncButtons(){const hasText=editor.value.trim().length>0;const hasResult=state.results.some((row)=>row&&(!row.error)&&row.columns&&row.columns.length>0);document.getElementById('run').disabled=!hasText;document.getElementById('explain').disabled=!hasText;document.getElementById('export').disabled=!hasResult;}
vscode.postMessage({command:'ready'});vscode.postMessage({command:'loadHistory',offset:0});syncButtons();
</script>`;
}

export function createNonce(): string {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    return Array.from({ length: 32 }, () => alphabet[Math.floor(Math.random() * alphabet.length)]).join('');
}

export function escapeHtml(value: string): string {
    return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character] ?? character));
}
